### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by crtgregoric**
Added Package.swift for supporting Swift Package Manager.

### CODE REVIEW

**Comment by hmhv** [comment]
Thank you for your PR!
but  when i test your fixed branch with SMP,  i can't load default template html with error. so i cant play youtube.
do you have any idea?

```
Received error rendering template: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
```

**Comment by crtgregoric** [comment]
@hmhv I'm not exactly sure what the testing scenario is. Are you talking about the `youtube-player-ios-example` subfolder? Is there any other example project where I could reproduce the issue?

**Comment by hmhv** [comment]
This is my test steps

1. make new ios project (UIKit, Swift)
2. add `YoutubePlayer-in-WKWebView` with SPM (spm-support branch on crtgregoric/YoutubePlayer-in-WKWebView.)
スクリーンショット 2021-02-06 10 18 41

3. add code to play
 ```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        playerView.load(withVideoId: "M7lc1UVf-VE", playerVars: [
            "controls" : 0,
            "playsinline" : 1,
            "autohide" : 1,
            "showinfo" : 0,
            "modestbranding" : 1
        ])
    }

```

4. build & run
5. error printed in output console
 ```
Received error rendering template: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid.
```

**Comment by crtgregoric** [comment]
I was able to reproduce the issue and it turned out the `WKYTPlayerView.bundle` was not added to the bundle. I fixed the issue. SPM seems to handle resources a bit differently (putting them inside a separate .bundle) so I added a preprocess macro that I'm checking in `WKYTPlayerView.frameworkBundle`. It's not the most elegant solution but it works.

**Pull request merged**
